/**
 * @name CS_const_Log
 * @description Constants for Log object
 */
public class CS_const_Log {
    /**
     * Picklist Values
     */
    public static final String JobType_Future = 'Future';
    public static final String JobType_Scheduled = 'Scheduled';
    public static final String JobType_Queueable = 'Queueable';
    public static final String JobType_Batch = 'Batch';
    public static final String JobType_WebService = 'Web Service';
}