/**
 * @name CS_const_RevenueScheduleItem
 * @description Constants for CS_Revenue_Schedule_Item__c object
 */
public with sharing class CS_const_RevenueScheduleItem {
	/**
	 * Picklist Values
	 */
	public static final String Status_Open = 'Open';
	public static final String Status_Locked = 'Locked';
	public static final String Status_Pending = 'Pending';
	public static final String Status_PendingClosure = 'Pending Closure';
	public static final String Status_Ready = 'Ready';
	public static final String Status_Closed = 'Closed';
	public static final String Status_Forecast = 'Forecast';

	public static final String RevRecCalendar_Standard = 'Standard';
}